### ISSUE TITLE
OTF are corrupted?

### ISSUE THREAD

**Issue by itamarst** [Omnibus-Type/Rosario#1]
I tried updating to the OTFs here, and they didn't work (showed weird characters instead of correct text). TTFs did work.

I was previously using OTFs downloaded to omnibus-type.com and those worked fine.

**Comment by Omnibus-Type** [comment]
Hi @itamarst,

We are concerned about your issue, but we would like you to help us to reproduce it. So far we run the OTF fonts of the repo through our validation tests and everything is working as expected. But if you help us to answer the following question we could have a better idea in where is lying the issue.

1. Tell us the platform in which you saw the error.
2. Were you using an App, which app?
3. Where you typing or just changing the font of a text that was already set in another font
4. Was a text that was using an early version of Rosario?

Thanks

**Comment by itamarst** [comment]
Thanks for getting back to me!

I am on Linux, Ubuntu 16.04. I downloaded the OTFs to `~/.fonts`, and set it as default font in Firefox. Result was pages that looked like gibberish. I will try again and see what happens.

**Comment by itamarst** [comment]
Working OK on my Fedora box... maybe I did something wrong? I will try again on my work machine where I originally had the problem later today.

**Comment by itamarst** [comment]
I redownloaded the fonts using the same command line I did last time... and this time it worked. So, this was either my fault or a temporary download blip. So my apologies for wasting your time.
