### ISSUE TITLE
No property `font-variant-numeric` on Google Font

### ISSUE THREAD

**Issue by juliendms** [Omnibus-Type/Rosario#6]
From the `README.md`, the text `a4` looks like this:
![image](https://user-images.githubusercontent.com/41991731/100844373-14885480-347c-11eb-91f7-4619fe48876e.png)

From Google Fonts, it looks like this:
![image](https://user-images.githubusercontent.com/41991731/100844464-3386e680-347c-11eb-84af-a1d23775dae1.png)

I would like to have the numbers aligned on the baseline (just like the example in the README). Usually, there is a property in CSS that allows to do that:
`font-variant-numeric: lining-nums;`
Or
`font-feature-settings: "lnum" 1`

However, this does not work. Any idea how to make it work ? Is Google Fonts not up to date ?

**Comment by Omnibus-Type** [comment]
@juliendms check again the new fonts exported, it should work, at least in the software where we have designed and tested it is working

**Comment by juliendms** [comment]
It's working perfectly now, thanks ! Issue closed.
