### ISSUE TITLE
Please add Medium instance

### ISSUE THREAD

**Issue by thlinard** [Omnibus-Type/Rosario#7]
See google/fonts#3411

**Comment by Omnibus-Type** [comment]
@thlinard We added the Medium instance and export the fonts again, if you can take a look we would appreciate it. Many thanks!

**Comment by thlinard** [comment]
@Omnibus-Type The tables are good, but the current version on Google Fonts has a Light instance, and this one is missing in this new version.

**Comment by aaronbell** [comment]
@thlinard It looks like the Light instance is actually extrapolated and so at a lower quality level than the other instances. It would be best if a proper light were to be designed. In the meanwhile, I'd probably suggest removing the Light weight for the time being, but that might cause some issues. 

@m4rc1e @davelab6 — what is your view on this?

**Comment by aaronbell** [comment]
Actually, it looks like the "Light" instance doesn't even work in the version on Google Fonts, and (of course) any extrapolated instance must be within the defined space, so we can't even have an extrapolated Light instance in the variable font. 

I guess the question is, if we want to duplicate functionality that is presently on GF, then we need to add the extrapolated Light as a master in the Glyphs file. Or should we just leave it off for the time being and stick with the designed masters?

**Comment by thlinard** [comment]
@aaronbell It's strange, because the previous version, as presented in the README.md, has a Light version:

<img width="488" alt="Sample of Rosario." src="https://raw.githubusercontent.com/Omnibus-Type/Rosario/master/sources/Rosario-01.png">

But you're right, the "Light" instance doesn't even work in the version on Google Fonts. What does @Omnibus-Type think?

**Comment by aaronbell** [comment]
Yeah, as I said, the previous version had an extrapolated light. They removed it for this new version (which seems sensible do me) but due to backwards compatibility we might want to re-add it.

**Comment by thlinard** [comment]
Ah, OK, I hadn't looked at the sources. In this case, the most sensible idea is probably indeed to add the extrapolated Light as a master in the Glyphs file.
